#!/bin/sh

set -e

if [ -x "`which xdg-icon-resource`" ]; then
	xdg-icon-resource uninstall --novendor --size 48 \
		--context mimetypes \
		/usr/share/ManPageEditor/icons/48/maneditdoc.png \
		application-x-maneditdoc
	xdg-icon-resource uninstall --novendor --size 128 \
		--context mimetypes \
		/usr/share/ManPageEditor/icons/128/maneditdoc.png \
		application-x-maneditdoc
	xdg-icon-resource uninstall --novendor --size 256 \
		--context mimetypes \
		/usr/share/ManPageEditor/icons/256/maneditdoc.png \
		application-x-maneditdoc
	xdg-mime uninstall /usr/share/ManPageEditor/maneditdoc-mime.xml
fi

#DEBHELPER#

exit 0

